name: TeriumBridge
version: '${version}'
main: cloud.terium.bridge.bukkit.BridgeBukkitStartup
author: Jxnnik
description: TeriumBridge for Jxnnik's Cloud

commands:
  stop:
    aliases: shutdown, restart